from .employee.create_employee_view import CreateEmployeeView
from .employee.delete_employee_view import DeleteEmployeeView
from .employee.detail_employee_view import DetailEmployeeView
from .employee.list_employees_view import ListEmployeesView
from .employee.update_employee_view import UpdateEmployeeView

from .function.create_function_view import CreateFunctionView
from .function.delete_function_view import DeleteFunctionView
from .function.list_functions_view import ListFunctionsView
from .function.update_function_view import UpdateFunctionView