# Generated by Django 5.2.6 on 2025-09-14 20:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f3018eca-f4b5-4567-8424-d2eb42b69f94'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nome interno para identificar a conta (ex: Conta Principal)', max_length=200)),
                ('bank', models.CharField(choices=[('Inter', 'Banco Inter'), ('BB', 'Banco do Brasil'), ('Bradesco', 'Bradesco'), ('Itau', 'Itaú Unibanco'), ('Santander', 'Banco Santander'), ('Caixa', 'Caixa Econômica Federal'), ('Nubank', 'Nubank'), ('BTG', 'BTG Pactual'), ('Safra', 'Banco Safra'), ('C6', 'C6 Bank'), ('Sicoob', 'Sicoob'), ('Sicredi', 'Sicredi'), ('Original', 'Banco Original'), ('PagBank', 'PagBank (Banco Seguro)')], max_length=60)),
                ('agency', models.CharField(help_text='Número da agência bancária', max_length=10)),
                ('account_number', models.CharField(help_text='Número da conta bancária', max_length=20)),
                ('account_type', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança'), ('investimento', 'Conta de Investimento'), ('caixa', 'Caixa Interno / Dinheiro em Mãos')], max_length=20)),
                ('initial_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(choices=[('BRL', 'Real Brasileiro (R$)'), ('USD', 'Dólar Americano (US$)'), ('EUR', 'Euro (€)'), ('GBP', 'Libra Esterlina (£)'), ('JPY', 'Iene Japonês (¥)')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
    ]
