# Generated by Django 5.2.6 on 2025-09-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='initial_value',
        ),
    ]
