# Generated by Django 5.2.6 on 2025-09-12 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3e601bab-b6b9-4556-b361-d209ad74ce13'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3e601bab-b6b9-4556-b361-d209ad74ce13'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='employees/')),
                ('is_active', models.BooleanField(default=True)),
                ('admission_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workload', models.IntegerField(default=40)),
                ('employment_type', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('Intern', 'Estagiário'), ('Freelancer', 'Freelancer')], max_length=50)),
                ('obs', models.TextField(blank=True, null=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.functionmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
