# Generated by Django 5.2.6 on 2025-09-13 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='employment_type',
            field=models.CharField(choices=[('CLT', 'CLT'), ('At', 'Autônomo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e1a5321-0243-42be-86f8-2d82c47af3c5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='functionmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e1a5321-0243-42be-86f8-2d82c47af3c5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
