# Generated by Django 5.2.6 on 2025-09-13 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeemodel_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c297b674-2cd4-4a65-9997-2adb1fd1ed79'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
        migrations.AlterField(
            model_name='functionmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c297b674-2cd4-4a65-9997-2adb1fd1ed79'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
