# Generated by Django 5.2.6 on 2025-09-13 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeemodel_id_alter_employeemodel_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44f0d27a-acf8-48ec-8ded-7d84bdd2550c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='functionmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44f0d27a-acf8-48ec-8ded-7d84bdd2550c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
