# Generated by Django 5.2.6 on 2025-09-14 20:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeemodel_id_alter_functionmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f3018eca-f4b5-4567-8424-d2eb42b69f94'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='functionmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f3018eca-f4b5-4567-8424-d2eb42b69f94'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
