# Generated by Django 5.2.6 on 2025-09-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeemodel_id_alter_functionmodel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemodel',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='functionmodel',
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
    ]
