# Generated by Django 5.2.6 on 2025-09-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionmodel',
            name='payment_type',
            field=models.CharField(choices=[('hour', 'Por hora'), ('day', 'Por dia'), ('week', 'Por semana'), ('month', 'Por mês'), ('year', 'Por ano'), ('m2', 'Por metro quadrado'), ('task', 'Por tarefa/serviço'), ('contract', 'Contrato fechado (empreitada/preço fixo)'), ('commission', 'Comissão (%)'), ('unit', 'Por unidade produzida')], default='day', max_length=50),
        ),
    ]
