# Generated by Django 5.2.6 on 2025-09-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_functionmodel_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionmodel',
            name='payment_type',
            field=models.CharField(choices=[('hour', 'Por hora'), ('day', 'Por dia'), ('week', 'Por semana'), ('month', 'Por mês'), ('m2', 'Por metro quadrado'), ('task', 'Por tarefa/serviço'), ('contract', 'Contrato fechado (empreitada/preço fixo)')], default='day', max_length=50),
        ),
    ]
