# Generated by Django 5.2.6 on 2025-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_functionmodel_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionmodel',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
