# Generated by Django 5.2.6 on 2025-10-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_functionmodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='workload',
            field=models.IntegerField(blank=True, default=40, null=True),
        ),
    ]
