# Generated by Django 5.2.6 on 2025-10-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employeemodel_workload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='workload',
        ),
    ]
