# Generated by Django 5.2.6 on 2025-10-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_employeemodel_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionmodel',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='payment_type',
            field=models.CharField(choices=[('hour', 'Por hora'), ('day', 'Por dia'), ('week', 'Por semana'), ('month', 'Por mês'), ('m2', 'Por metro quadrado'), ('task', 'Por tarefa/serviço'), ('contract', 'Contrato fechado (empreitada/preço fixo)')], default='day', max_length=50),
        ),
    ]
