# Generated by Django 5.2.6 on 2025-11-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_functionmodel_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='payment_type',
        ),
    ]
